#include "src/game/envfx_snow.h"

const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Half_Eyes__SKIN__0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Half_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt1),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt2),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt3),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt4),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt5),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt6),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Left_Hand_Open[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, -23, 1, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Right_Hand_Open[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Right_Hand_Peace[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Left_Hand_Cap[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Left_Hand_Wing_Cap[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Metal_Mario_Switch_Option_Capless_Head_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Metal_Mario_Switch_Option_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Metal_Mario_Switch_Option_Left_Hand_Open_Metal[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, -23, 1, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Metal_Mario_Switch_Option_Right_Hand_Open_Metal[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Metal_Mario_Switch_Option_Left_Hand_Cap_Metal[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Cap_Metal[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Capless_Head_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Left_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, -23, 1, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Right_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Left_Hand_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -2, 0, 0, gustavo_Metal_Mario_Switch_Option_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Head_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Capless_Head_Metal),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, 150, -25, 20, -129),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, -1, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, -150, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, 89, NULL),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 2, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Left_Hand_Open_Metal),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, -89, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 1, -19, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Right_Hand_Open_Metal),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Left_Hand_Cap_Metal),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Cap_Metal),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, 82, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 57, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Shoe_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, -82, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Metal_Mario_Switch_Option_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_Gustavo_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, 0, gustavo_Metal_Mario_Switch_Option_Torso_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Metal_Mario_Switch_Option_Head_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, gustavo_Metal_Mario_Switch_Option_Capless_Head_Metal),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, 150, -25, 20, -129),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, -1, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Metal_Mario_Switch_Option_Left_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, -150, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Metal_Mario_Switch_Option_Right_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, 89, NULL),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 2, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Arm_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Metal_Mario_Switch_Option_Left_Hand_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, gustavo_Metal_Mario_Switch_Option_Left_Hand_Open_Metal),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, -89, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, gustavo_Metal_Mario_Switch_Option_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Metal_Mario_Switch_Option_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 1, -19, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, gustavo_Metal_Mario_Switch_Option_Right_Hand_Open_Metal),
												GEO_BRANCH(1, gustavo_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal),
												GEO_BRANCH(1, gustavo_Metal_Mario_Switch_Option_Left_Hand_Cap_Metal),
												GEO_BRANCH(1, gustavo_Metal_Mario_Switch_Option_Left_Hand_Wing_Cap_Metal),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, 82, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, gustavo_Metal_Mario_Switch_Option_Left_Shoe_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, -82, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Metal_Mario_Switch_Option_Right_Shoe_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Half_Eyes__SKIN__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Half_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt1),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt2),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt3),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt4),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt5),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt6),
			GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, -23, 1, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Left_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Left_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, -19, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1_mat_override_Half_Eyes__SKIN__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4_mat_override_Half_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -2, 0, 0, gustavo_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Head_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, 150, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, -150, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, 89, NULL),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 2, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, gustavo_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, -89, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, gustavo_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 85, 0, 0, gustavo_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 1, -19, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Right_Hand_Open),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Right_Hand_Peace),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Left_Hand_Cap),
										GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_gustavo_Left_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, 82, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 57, 0, 0, gustavo_Left_Shoe_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, -82, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gustavo_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1_mat_override_Half_Eyes__SKIN__0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4_mat_override_Half_Eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1_mat_override_Closed_Eyes__SKIN__1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4_mat_override_Closed_Eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1_mat_override_Left_Eyes__SKIN__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4_mat_override_Left_Eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1_mat_override_Right_Eyes__SKIN__3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4_mat_override_Right_Eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1_mat_override_Up_Eyes__SKIN__4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4_mat_override_Up_Eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1_mat_override_Down_Eyes__SKIN__5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4_mat_override_Down_Eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1_mat_override_Dead_Eyes__SKIN__6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4_mat_override_Dead_Eyes__SKIN__6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gustavo_skl_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -2, 0, 0, gustavo_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Head_DL_mesh_layer_1),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Head_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
																	GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
																	GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
																	GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
																	GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
																	GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
																	GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, gustavo_Capless_Head),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, 150, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -71, -150, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, gustavo_Right_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, 89, NULL),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 2, 0, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Left_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, gustavo_Left_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(1, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Left_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, gustavo_Left_Hand_Open),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -30, -89, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, gustavo_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 85, 0, 0, gustavo_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Right_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 1, -19, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, gustavo_Right_Hand_Open),
																GEO_BRANCH(1, gustavo_Right_Hand_Peace),
																GEO_BRANCH(1, gustavo_Left_Hand_Cap),
																GEO_BRANCH(1, gustavo_Left_Hand_Wing_Cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, 82, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, gustavo_Left_Shoe_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -8, -82, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, gustavo_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, gustavo_2_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, gustavo_Gustavo_Metal),
							GEO_BRANCH(1, gustavo_Gustavo_Metal),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
