extern const GeoLayout peppino_cap_metal_Metal_Cap_State_Switch_opt1[];
extern const GeoLayout peppino_cap_metal_Metal_Cap_State_Switch_opt2[];
extern const GeoLayout peppino_cap_metal_Metal_Cap_State_Switch_opt3[];
extern const GeoLayout peppino_skl_cap_metal_geo[];
extern Lights1 peppino_cap_metal_metal_lights;
extern u8 peppino_cap_metal_Metal_Shade_rgba16_rgba16[];
extern u8 peppino_cap_metal_Metal_Light_rgba16_rgba16[];
extern Vtx peppino_cap_metal_Metal_Cap_DL_mesh_layer_1_vtx_0[63];
extern Gfx peppino_cap_metal_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_peppino_cap_metal_metal[];
extern Gfx mat_revert_peppino_cap_metal_metal[];
extern Gfx peppino_cap_metal_Metal_Cap_DL_mesh_layer_1[];
extern Gfx peppino_cap_metal_Metal_Cap_DL_mesh_layer_1_mat_override_metal_0[];
