extern const GeoLayout homer_cap_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout homer_cap_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout homer_cap_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout homer_skl_cap_wing_geo[];
extern Lights1 homer_cap_wing_CAP_duff_lights;
extern Lights1 homer_cap_wing_METAL_lights;
extern u8 homer_cap_wing_duff_beer_nocolor_ci4[];
extern u8 homer_cap_wing_duff_beer_nocolor_pal_rgba16[];
extern u8 homer_cap_wing_Metal_Shade_rgba16_rgba16[];
extern u8 homer_cap_wing_Metal_Light_rgba16_rgba16[];
extern u8 homer_cap_wing_wing_2_rgba16[];
extern u8 homer_cap_wing_wing1_rgba16[];
extern Vtx homer_cap_wing_Wing_Cap_mesh_layer_1_vtx_0[28];
extern Gfx homer_cap_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx homer_cap_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx homer_cap_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx homer_cap_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx homer_cap_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_homer_cap_wing_CAP_duff[];
extern Gfx mat_revert_homer_cap_wing_CAP_duff[];
extern Gfx mat_homer_cap_wing_METAL[];
extern Gfx mat_revert_homer_cap_wing_METAL[];
extern Gfx mat_homer_cap_wing_Wing_Tip[];
extern Gfx mat_revert_homer_cap_wing_Wing_Tip[];
extern Gfx mat_homer_cap_wing_Wing_Base[];
extern Gfx mat_revert_homer_cap_wing_Wing_Base[];
extern Gfx homer_cap_wing_Wing_Cap_mesh_layer_1[];
extern Gfx homer_cap_wing_Wing_Cap_mesh_layer_1_mat_override_METAL_0[];
extern Gfx homer_cap_wing_Wings_mesh_layer_4[];
extern Gfx homer_cap_wing_Wings_mesh_layer_4_mat_override_METAL_0[];
