extern const GeoLayout peppino_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout peppino_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout peppino_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout peppino_skl_cap_geo[];
extern Lights1 peppino_cap_CAP_lights;
extern Lights1 peppino_cap_UNDERCAP_lights;
extern Lights1 peppino_cap_metal_lights;
extern u8 peppino_cap_Metal_Shade_rgba16_rgba16[];
extern u8 peppino_cap_Metal_Light_rgba16_rgba16[];
extern Vtx peppino_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[58];
extern Gfx peppino_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx peppino_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[8];
extern Gfx peppino_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_peppino_cap_CAP[];
extern Gfx mat_peppino_cap_UNDERCAP[];
extern Gfx mat_peppino_cap_metal[];
extern Gfx mat_revert_peppino_cap_metal[];
extern Gfx peppino_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx peppino_cap_Normal_Cap_DL_mesh_layer_1_mat_override_metal_0[];
