extern const GeoLayout gustavo_skl_cap_geo[];
extern Lights1 gustavo_cap_CAP_lights;
extern Lights1 gustavo_cap_UNDERCAP_lights;
extern Vtx gustavo_cap_Cap_mesh_layer_1_vtx_0[124];
extern Gfx gustavo_cap_Cap_mesh_layer_1_tri_0[];
extern Vtx gustavo_cap_Cap_mesh_layer_1_vtx_1[10];
extern Gfx gustavo_cap_Cap_mesh_layer_1_tri_1[];
extern Gfx mat_gustavo_cap_CAP[];
extern Gfx mat_gustavo_cap_UNDERCAP[];
extern Gfx gustavo_cap_Cap_mesh_layer_1[];
