extern const GeoLayout papyrus_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout papyrus_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout papyrus_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout papyrus_skl_cap_geo[];
extern Lights1 papyrus_cap_Cape__CAP__lights;
extern Lights1 papyrus_cap_Cape_shadow__CAP__lights;
extern Lights1 papyrus_cap_Metal__METAL__lights;
extern u8 papyrus_cap_Metal_Shade_rgba16_rgba16[];
extern u8 papyrus_cap_Metal_Light_rgba16_rgba16[];
extern Vtx papyrus_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[28];
extern Gfx papyrus_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx papyrus_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[11];
extern Gfx papyrus_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_papyrus_cap_Cape__CAP_[];
extern Gfx mat_papyrus_cap_Cape_shadow__CAP_[];
extern Gfx mat_papyrus_cap_Metal__METAL_[];
extern Gfx mat_revert_papyrus_cap_Metal__METAL_[];
extern Gfx papyrus_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx papyrus_cap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
