#include "src/game/envfx_snow.h"

const GeoLayout sans_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Half_eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Close_eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Left_eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Right_eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Up_eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Down_eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Capless_Torso[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 35, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Capless_Torso_Switch_Option_Torso_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mario_head_rotation),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6),
								GEO_BRANCH(1, sans_Head_Dead),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
					GEO_OPEN_NODE(),
						GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Capless_Torso_Switch_Option_Left_Wing_DL_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Capless_Torso_Switch_Option_Right_Wing_DL_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Capless_Torso_Switch_Option_Left_Arm_Color_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Capless_Torso_Switch_Option_Left_Forearm_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(1, geo_switch_mario_hand),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Left_Hand_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, sans_Left_Hand_Open),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Capless_Torso_Switch_Option_Right_Arm_Color_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Capless_Torso_Switch_Option_Right_Forearm_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_hand),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Capless_Torso_Switch_Option_Right_Hand_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, sans_Right_Hand_Open),
							GEO_BRANCH(1, sans_Right_Hand_Peace),
							GEO_BRANCH(1, sans_Right_Hand_Cap),
							GEO_BRANCH(1, sans_Right_Hand_Wing_Cap),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Metal_Mario_Switch_Option_Left_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Metal_Mario_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Metal_Mario_Switch_Option_Right_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Metal_Mario_Switch_Option_Capless_Torso_Metal[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 35, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Torso_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mario_head_rotation),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
					GEO_OPEN_NODE(),
						GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Wing_DL_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Wing_DL_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Arm_Color_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Forearm_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(1, geo_switch_mario_hand),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Hand_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Left_Hand_Open_Metal),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Arm_Color_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Forearm_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_hand),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Hand_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Open_Metal),
							GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal),
							GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Metal),
							GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Metal),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Left_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Left_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Open_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 35, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Torso_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_mario_head_rotation),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Wing_DL_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Wing_DL_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Arm_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Forearm_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(1, geo_switch_mario_hand),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Left_Hand_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Left_Hand_Open_Metal),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Arm_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Forearm_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_hand),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Capless_Torso_Switch_Option_Right_Hand_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Open_Metal),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Metal),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Metal),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 35, 0, 0, sans_Metal_Mario_Switch_Option_Torso_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Head_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Left_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Right_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Metal_Mario_Switch_Option_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Left_Hand_Open_Metal),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Metal_Mario_Switch_Option_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Open_Metal),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Metal),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Metal),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_sans_Metal_Mario_Switch_Option_Capless_Torso_Metal),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, 62, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, -1, 0, sans_Metal_Mario_Switch_Option_Left_Shoe_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, -62, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Metal_Mario_Switch_Option_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 61, -1, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Metal_Mario_Switch_Option_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_Sans_Metal[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Butt_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 35, 0, 0, sans_Metal_Mario_Switch_Option_Torso_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_head_rotation),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Metal_Mario_Switch_Option_Head_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Metal_Mario_Switch_Option_Left_Wing_DL_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Metal_Mario_Switch_Option_Right_Wing_DL_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Left_Arm_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Metal_Mario_Switch_Option_Left_Forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(1, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Metal_Mario_Switch_Option_Left_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Left_Hand_Open_Metal),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Right_Arm_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Metal_Mario_Switch_Option_Right_Forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Metal_Mario_Switch_Option_Right_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
																GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Open_Metal),
														GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Peace_Metal),
														GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Cap_Metal),
														GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Right_Hand_Wing_Cap_Metal),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, sans_Metal_Mario_Switch_Option_Capless_Torso_Metal),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, 62, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Left_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Metal_Mario_Switch_Option_Left_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 61, -1, 0, sans_Metal_Mario_Switch_Option_Left_Shoe_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, -62, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Metal_Mario_Switch_Option_Right_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Metal_Mario_Switch_Option_Right_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 61, -1, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Metal_Mario_Switch_Option_Right_Shoe_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Half_eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Close_eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Left_eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Right_eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Up_eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1_mat_override_Down_eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 35, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Capless_Torso_Switch_Option_Torso_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_mario_head_rotation),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Head_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1),
									GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2),
									GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3),
									GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4),
									GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5),
									GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6),
									GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Head_Dead),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Left_Wing_DL_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Right_Wing_DL_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Capless_Torso_Switch_Option_Left_Arm_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Capless_Torso_Switch_Option_Left_Forearm_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(1, geo_switch_mario_hand),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Left_Hand_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Left_Hand_Open),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Capless_Torso_Switch_Option_Right_Arm_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Capless_Torso_Switch_Option_Right_Forearm_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_hand),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Capless_Torso_Switch_Option_Right_Hand_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Open),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Peace),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Cap),
								GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso_jump_sans_Right_Hand_Wing_Cap),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_DL_mesh_layer_1_mat_override_Half_eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_DL_mesh_layer_1_mat_override_Close_eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_DL_mesh_layer_1_mat_override_Left_eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_DL_mesh_layer_1_mat_override_Right_eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_DL_mesh_layer_1_mat_override_Up_eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_DL_mesh_layer_1_mat_override_Down_eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 35, 0, 0, sans_Torso_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Head_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1),
													GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2),
													GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3),
													GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4),
													GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5),
													GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6),
													GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Head_Dead),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Left_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Right_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Left_Hand_Open),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 54, 0, 0, sans_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Open),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Peace),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Cap),
												GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_sans_Capless_Torso),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, 62, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, -1, 0, sans_Left_Shoe_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, -62, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sans_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 73, 0, 0, sans_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 61, -1, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sans_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_DL_mesh_layer_1_mat_override_Half_eyes__SKIN__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_DL_mesh_layer_1_mat_override_Close_eyes__SKIN__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_DL_mesh_layer_1_mat_override_Left_eyes__SKIN__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_DL_mesh_layer_1_mat_override_Right_eyes__SKIN__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_DL_mesh_layer_1_mat_override_Up_eyes__SKIN__4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_DL_mesh_layer_1_mat_override_Down_eyes__SKIN__5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sans_skl_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 35, 0, 0, sans_Torso_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 156, -34, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_head_rotation),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																		GEO_OPEN_NODE(),
																			GEO_NODE_START(),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Head_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1),
																			GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2),
																			GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3),
																			GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4),
																			GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5),
																			GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Torso_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6),
																			GEO_BRANCH(1, sans_Head_Dead),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, 126, -15, 33, -133),
																GEO_OPEN_NODE(),
																	GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
																	GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Left_Wing_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_TRANSLATE_ROTATE(LAYER_FORCE, 106, -17, -126, 15, -33, -133),
																GEO_OPEN_NODE(),
																	GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
																	GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, sans_Right_Wing_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 89, -21, 99, NULL),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Left_Arm_Color_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Left_Forearm_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(1, geo_mario_hand_foot_scaler),
																				GEO_SCALE(LAYER_FORCE, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Left_Hand_DL_mesh_layer_1),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, sans_Left_Hand_Open),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 90, -21, -99, NULL),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Right_Arm_Color_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, sans_Right_Forearm_mesh_layer_1),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(0, geo_mario_hand_foot_scaler),
																				GEO_SCALE(LAYER_FORCE, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Right_Hand_DL_mesh_layer_1),
																				GEO_CLOSE_NODE(),
																				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, sans_Right_Hand_Open),
																		GEO_BRANCH(1, sans_Right_Hand_Peace),
																		GEO_BRANCH(1, sans_Right_Hand_Cap),
																		GEO_BRANCH(1, sans_Right_Hand_Wing_Cap),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, sans_Capless_Torso),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, 62, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 61, -1, 0, sans_Left_Shoe_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -7, 0, -62, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sans_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, sans_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 61, -1, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, sans_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, sans_2_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, sans_Sans_Metal),
							GEO_BRANCH(1, sans_Sans_Metal),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
