extern const GeoLayout noise_cap_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout noise_cap_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout noise_cap_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout noise_skl_cap_wing_geo[];
extern Lights1 noise_cap_wing_CAP_lights;
extern Lights1 noise_cap_wing_UNDERCAP_lights;
extern Lights1 noise_cap_wing_HAIR_lights;
extern Lights1 noise_cap_wing_Metal_lights;
extern u8 noise_cap_wing_Metal_Shade_rgba16_rgba16[];
extern u8 noise_cap_wing_Metal_Light_rgba16_rgba16[];
extern u8 noise_cap_wing_wing_2_ia8[];
extern u8 noise_cap_wing_wing1_ia8[];
extern Vtx noise_cap_wing_Wing_Cap_mesh_layer_1_vtx_0[62];
extern Gfx noise_cap_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx noise_cap_wing_Wing_Cap_mesh_layer_1_vtx_1[8];
extern Gfx noise_cap_wing_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx noise_cap_wing_Wing_Cap_mesh_layer_1_vtx_2[37];
extern Gfx noise_cap_wing_Wing_Cap_mesh_layer_1_tri_2[];
extern Vtx noise_cap_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx noise_cap_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx noise_cap_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx noise_cap_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_noise_cap_wing_CAP[];
extern Gfx mat_noise_cap_wing_UNDERCAP[];
extern Gfx mat_noise_cap_wing_HAIR[];
extern Gfx mat_noise_cap_wing_Metal[];
extern Gfx mat_revert_noise_cap_wing_Metal[];
extern Gfx mat_noise_cap_wing_Wing_Tip[];
extern Gfx mat_revert_noise_cap_wing_Wing_Tip[];
extern Gfx mat_noise_cap_wing_Wing_Base[];
extern Gfx mat_revert_noise_cap_wing_Wing_Base[];
extern Gfx noise_cap_wing_Wing_Cap_mesh_layer_1[];
extern Gfx noise_cap_wing_Wing_Cap_mesh_layer_1_mat_override_Metal_0[];
extern Gfx noise_cap_wing_Wings_mesh_layer_4[];
extern Gfx noise_cap_wing_Wings_mesh_layer_4_mat_override_Metal_0[];
