extern const GeoLayout peppino_cap_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout peppino_cap_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout peppino_cap_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout peppino_skl_cap_wing_geo[];
extern Lights1 peppino_cap_wing_CAP_lights;
extern Lights1 peppino_cap_wing_UNDERCAP_lights;
extern Lights1 peppino_cap_wing_metal_lights;
extern u8 peppino_cap_wing_Metal_Shade_rgba16_rgba16[];
extern u8 peppino_cap_wing_Metal_Light_rgba16_rgba16[];
extern u8 peppino_cap_wing_wing_2_ia8[];
extern u8 peppino_cap_wing_wing1_ia8[];
extern Vtx peppino_cap_wing_Wing_Cap_mesh_layer_1_vtx_0[59];
extern Gfx peppino_cap_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx peppino_cap_wing_Wing_Cap_mesh_layer_1_vtx_1[8];
extern Gfx peppino_cap_wing_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx peppino_cap_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx peppino_cap_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx peppino_cap_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx peppino_cap_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_peppino_cap_wing_CAP[];
extern Gfx mat_peppino_cap_wing_UNDERCAP[];
extern Gfx mat_peppino_cap_wing_metal[];
extern Gfx mat_revert_peppino_cap_wing_metal[];
extern Gfx mat_peppino_cap_wing_Wing_Tip[];
extern Gfx mat_revert_peppino_cap_wing_Wing_Tip[];
extern Gfx mat_peppino_cap_wing_Wing_Base[];
extern Gfx mat_revert_peppino_cap_wing_Wing_Base[];
extern Gfx peppino_cap_wing_Wing_Cap_mesh_layer_1[];
extern Gfx peppino_cap_wing_Wing_Cap_mesh_layer_1_mat_override_metal_0[];
extern Gfx peppino_cap_wing_Wings_mesh_layer_4[];
extern Gfx peppino_cap_wing_Wings_mesh_layer_4_mat_override_metal_0[];
