extern const GeoLayout maurice_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout maurice_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout maurice_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout maurice_cap_geo[];
extern Lights1 maurice_cap_CAP_lights;
extern Lights1 maurice_cap_UNDERCAP_lights;
extern Lights1 maurice_cap_Metal_lights;
extern u8 maurice_cap_Metal_Shade_rgba16_rgba16[];
extern u8 maurice_cap_Metal_Light_rgba16_rgba16[];
extern Vtx maurice_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[75];
extern Gfx maurice_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx maurice_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[8];
extern Gfx maurice_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_maurice_cap_CAP[];
extern Gfx mat_maurice_cap_UNDERCAP[];
extern Gfx mat_maurice_cap_Metal[];
extern Gfx mat_revert_maurice_cap_Metal[];
extern Gfx maurice_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx maurice_cap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal_0[];
