extern const GeoLayout sans_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout sans_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout sans_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout sans_skl_cap_geo[];
extern Lights1 sans_cap_Jacket__CAP__lights;
extern Lights1 sans_cap_Hood__GLOVES__lights;
extern Lights1 sans_cap_Back_Jacket__CAP__lights;
extern Lights1 sans_cap_Metal__METAL__lights;
extern u8 sans_cap_Metal_Shade_rgba16_rgba16[];
extern u8 sans_cap_Metal_Light_rgba16_rgba16[];
extern Vtx sans_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[88];
extern Gfx sans_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx sans_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[78];
extern Gfx sans_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx sans_cap_Normal_Cap_DL_mesh_layer_1_vtx_2[6];
extern Gfx sans_cap_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Gfx mat_sans_cap_Jacket__CAP_[];
extern Gfx mat_sans_cap_Hood__GLOVES_[];
extern Gfx mat_sans_cap_Back_Jacket__CAP_[];
extern Gfx mat_sans_cap_Metal__METAL_[];
extern Gfx mat_revert_sans_cap_Metal__METAL_[];
extern Gfx sans_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx sans_cap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
