extern const GeoLayout anton_skl_cap_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout anton_skl_cap_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout anton_skl_cap_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout anton_skl_cap_wing_geo[];
extern Lights1 anton_skl_cap_wing_Cap__CAP__lights;
extern Lights1 anton_skl_cap_wing_Metal__METAL__lights;
extern u8 anton_skl_cap_wing_Metal_Shade_rgba16_rgba16[];
extern u8 anton_skl_cap_wing_Metal_Light_rgba16_rgba16[];
extern u8 anton_skl_cap_wing_wing_2_rgba16[];
extern u8 anton_skl_cap_wing_wing1_rgba16[];
extern Vtx anton_skl_cap_wing_Wing_Cap_mesh_layer_1_vtx_0[60];
extern Gfx anton_skl_cap_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx anton_skl_cap_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx anton_skl_cap_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx anton_skl_cap_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx anton_skl_cap_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_anton_skl_cap_wing_Cap__CAP_[];
extern Gfx mat_anton_skl_cap_wing_Metal__METAL_[];
extern Gfx mat_revert_anton_skl_cap_wing_Metal__METAL_[];
extern Gfx mat_anton_skl_cap_wing_Wing_Tip[];
extern Gfx mat_revert_anton_skl_cap_wing_Wing_Tip[];
extern Gfx mat_anton_skl_cap_wing_Wing_Base[];
extern Gfx mat_revert_anton_skl_cap_wing_Wing_Base[];
extern Gfx anton_skl_cap_wing_Wing_Cap_mesh_layer_1[];
extern Gfx anton_skl_cap_wing_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx anton_skl_cap_wing_Wings_mesh_layer_4[];
extern Gfx anton_skl_cap_wing_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
