extern const GeoLayout brian_skl_cap_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout brian_skl_cap_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout brian_skl_cap_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout brian_skl_cap_wing_geo[];
extern Lights1 brian_skl_cap_wing_Collar__CAP__lights;
extern Lights1 brian_skl_cap_wing_Tag__GLOVES__lights;
extern Lights1 brian_skl_cap_wing_Collar_Black_lights;
extern Lights1 brian_skl_cap_wing_Metal__METAL__lights;
extern u8 brian_skl_cap_wing_Metal_Shade_rgba16_rgba16[];
extern u8 brian_skl_cap_wing_Metal_Light_rgba16_rgba16[];
extern u8 brian_skl_cap_wing_wing_2_rgba16[];
extern u8 brian_skl_cap_wing_wing1_rgba16[];
extern Vtx brian_skl_cap_wing_Wing_Cap_mesh_layer_1_vtx_0[26];
extern Gfx brian_skl_cap_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx brian_skl_cap_wing_Wing_Cap_mesh_layer_1_vtx_1[15];
extern Gfx brian_skl_cap_wing_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx brian_skl_cap_wing_Wing_Cap_mesh_layer_1_vtx_2[4];
extern Gfx brian_skl_cap_wing_Wing_Cap_mesh_layer_1_tri_2[];
extern Vtx brian_skl_cap_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx brian_skl_cap_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx brian_skl_cap_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx brian_skl_cap_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_brian_skl_cap_wing_Collar__CAP_[];
extern Gfx mat_revert_brian_skl_cap_wing_Collar__CAP_[];
extern Gfx mat_brian_skl_cap_wing_Tag__GLOVES_[];
extern Gfx mat_brian_skl_cap_wing_Collar_Black[];
extern Gfx mat_revert_brian_skl_cap_wing_Collar_Black[];
extern Gfx mat_brian_skl_cap_wing_Metal__METAL_[];
extern Gfx mat_revert_brian_skl_cap_wing_Metal__METAL_[];
extern Gfx mat_brian_skl_cap_wing_Wing_Tip[];
extern Gfx mat_revert_brian_skl_cap_wing_Wing_Tip[];
extern Gfx mat_brian_skl_cap_wing_Wing_Base[];
extern Gfx mat_revert_brian_skl_cap_wing_Wing_Base[];
extern Gfx brian_skl_cap_wing_Wing_Cap_mesh_layer_1[];
extern Gfx brian_skl_cap_wing_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx brian_skl_cap_wing_Wings_mesh_layer_4[];
extern Gfx brian_skl_cap_wing_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
