extern const GeoLayout noise_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout noise_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout noise_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout noise_skl_cap_geo[];
extern Lights1 noise_cap_CAP_lights;
extern Lights1 noise_cap_UNDERCAP_lights;
extern Lights1 noise_cap_HAIR_lights;
extern Lights1 noise_cap_Metal_lights;
extern u8 noise_cap_Metal_Shade_rgba16_rgba16[];
extern u8 noise_cap_Metal_Light_rgba16_rgba16[];
extern Vtx noise_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[62];
extern Gfx noise_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx noise_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[8];
extern Gfx noise_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx noise_cap_Normal_Cap_DL_mesh_layer_1_vtx_2[37];
extern Gfx noise_cap_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Gfx mat_noise_cap_CAP[];
extern Gfx mat_noise_cap_UNDERCAP[];
extern Gfx mat_noise_cap_HAIR[];
extern Gfx mat_noise_cap_Metal[];
extern Gfx mat_revert_noise_cap_Metal[];
extern Gfx noise_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx noise_cap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal_0[];
